version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    reviewers:
      - "eBayMobile/graph-analytics-plugin-team"
  - package-ecosystem: gradle
    directory: "/"
    schedule:
      interval: "daily"
    reviewers:
      - "eBayMobile/graph-analytics-plugin-team"
