name: PR Build
on:
  pull_request:
jobs:
  gradle:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
      - name: Build Plugin
        run: ./gradlew build
      - name: Sample Analysis
        working-directory: sample
        run: ../gradlew graphAnalysis
      - name: Sample Inspection
        working-directory: sample
        run: ../gradlew :app:graphInspection
