name: PR Build
on:
  pull_request:
jobs:
  gradle:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        # 8.11 = oldest supported version
        # wrapper = supposed to be the oldest supported version but actually runs current
        # current = latest stable version
        # release-candidate = next stable version
        # nightly = latest development version
        gradle-version: ["8.11", "wrapper", "current", "release-candidate", "nightly"]
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: 17
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v5
        with:
            gradle-version: ${{ matrix.gradle-version }}
            develocity-access-key: ${{ secrets.DEVELOCITY_ACCESS_KEY }}
      - name: Build Plugin
        run: gradle build
      - name: Sample Analysis
        working-directory: sample
        run: gradle graphAnalysis
      - name: Sample Inspection
        working-directory: sample
        run: gradle :app:graphInspection
