name: Publish Gradle Plugin
on: [workflow_dispatch]
#on:
#  release:
#    types: [published]
jobs:
  gradle:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
      - name: Build Plugin
        run: ./gradlew --no-configuration-cache publishPlugins --validate-only
